plugins:
  - rubocop-rails

AllCops:
  UseCache: false
  NewCops: enable

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "config/environments/development.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/**/*"

Metrics/ClassLength:
  Exclude:
    - "test/**/*"
